# Generated by Django 3.2.8 on 2021-10-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_remove_answer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='crate_date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='crate_date',
            field=models.DateTimeField(default=''),
        ),
    ]
