# Generated by Django 3.2.8 on 2021-10-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20211027_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='crate_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='crate_date',
            new_name='create_date',
        ),
    ]
