# Generated by Django 3.2.8 on 2021-10-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20211029_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='modify_data',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modify_data',
            new_name='modify_date',
        ),
    ]
